authe/urls.py
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from .views import UserCreate, NotFound
from . import views
app_name = 'authe'

urlpatterns=[
    path('oops/', NotFound.as_view(),name = 'oops'),
    path('login/', auth_views.LoginView.as_view(), name = 'login' ),
    path('logout/',auth_views.LogoutView.as_view(),name = 'logout'),
    path('signup/',UserCreate.as_view(),name = 'signup'),
    path('signup/confirm/',views.signup_confirm,name='signup_confirm'),
    path('signup/activate/<uidb64>/<token>/',views.activate,name='activate'),
    path('chpwd/', views.UserChangePassword.as_view(), name='chpwd'),
    path('chpwd/success', auth_views.PasswordChangeDoneView.as_view(), name ='chpwddone'),
    path('resetpwd/',views.UserResetPassword.as_view(),name ='pwdreset'),
    path('resetpwd/confirm/<uidb64>/<token>/', views.UserResetConfirm.as_view(), name='pwdresetconfirm'),
    path('resetpwd/done',auth_views.PasswordResetDoneView.as_view(),name = 'pwdresetdone'),
    path('resetpwd/complete/',auth_views.PasswordResetCompleteView.as_view(),name ='pwdresetcomp'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from authe import views as authe_view
from django.conf import settings
from . import views
urlpatterns = [
    path('authe/', include('authe.urls')),
    path('home/', include('home.urls')),
    path('posts/',include('post.urls')),
    path('', views.redir, name = 'home_redir'),
    path('martor/',include('martor.urls')),
    
]
if settings.ADMIN_ENABLED:
    urlpatterns += [path('admin/', admin.site.urls),]
    pass

handler404 = authe_view.NotFound.as_view()

home/urls.py
from django.urls import path

from . import views
app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/',views.about,name='about'),
    path('joinme/',views.joinme,name='joinme'),
]

post/urls.py
from django.urls import path

from . import views


app_name = 'post'
urlpatterns = [
    path('',views.index,name='index'),
    path('tags/<slug:tag_slug>/',views.tagIndex, name='index_tag'),
    path('create/',views.create,name='create'),
    path('<int:post_id>/', views.detail,name='detail'),
    path('edit/<int:post_id>/',views.edit, name= 'edit'),
    path('edit/tags/',views.editTags,name='edit_tag'),
    path('delete/<int:pk>/',views.PostDelete.as_view(),name='delete'),
]

post/models.py
from django.db import models
from martor.models import MartorField
from django.contrib.auth.models import User
from django.utils import timezone
#from django.utils.html import mark_safe
#from markdown import markdown
# Create your models here.


class Tag(models.Model):
    tag_text = models.CharField(max_length=255, unique=True)
    #description = models.Char
    def __str__(self):
        return self.tag_text
    pass


class Post(models.Model):
    class Meta:
        permissions = (("can_create", "Create Posts"),
                       ("can_edit", "Edit Posts"),
        )
        pass
    title = models.CharField(max_length=255)
    body = MartorField()#models.CharField(max_length=20000)
    tags = models.ManyToManyField(Tag)
    pub_date = models.DateTimeField('date published')
    # mod_date = models.DateTimeField('date modified')
    #def get_message_as_markdown(self):
    #    return mark_safe(markdown(self.body,safe_mode='escape'))
    #pass

    def __str__(self):
        return self.title
    pass



class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE);
    content = MartorField()
    created_date = models.DateTimeField('date published')
    pass

    

post/forms.py
from django.forms import ModelForm, Textarea
from .models import Post, Comment, Tag
from martor.widgets import MartorWidget
class PostForm(ModelForm):
    class Meta:
        model = Post
        fields =  ['title','tags', 'body']
        widgets = {
          'body': MartorWidget(attrs={'rows':50, 'cols':100}),
        }
        pass
    pass


class TagForm(ModelForm):
    class Meta:
        model = Tag
        fields =  ['tag_text']
        pass
    pass

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content':MartorWidget(attrs={'rows':20,'cols':100}),
        }
        pass
    
    def save(self, commit=True):
        comment = super(CommentForm,self).save(commit=False)
        if commit:
            comment.save()
            pass
        return comment
    pass

post/views.py
from django.shortcuts import get_object_or_404, render, reverse
from django.urls import reverse_lazy
from django.views.generic.edit import DeleteView, CreateView, UpdateView

from django.http import HttpResponse, HttpResponseRedirect
from .models import Post, Tag
from .forms import PostForm, CommentForm, TagForm
from django.utils import timezone
from django.forms import modelformset_factory
from django.contrib.auth.decorators import permission_required
from django.core.paginator import Paginator

def detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    tags = Tag.objects.filter(post__id=post_id)
    if (request.method == 'POST'):
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.created_date = timezone.now()
            new_comment.post = post
            new_comment.user = request.user
            new_comment.save()
            return render(request,'post/detail.html',{'post':post,'tags':tags,'form':form})
    else:
        form = CommentForm()
        pass
    return render(request, 'post/detail.html',{'post':post,'tags':tags,'form':form})



def index(request):
    post_lst = Post.objects.exclude(tags__tag_text="travel")
    paginator = Paginator(post_lst, 8)
    page = request.GET.get('page')
    post_list = paginator.get_page(page)
    context = {'post_list': post_list,'tagname':'Articles'}
    return render(request, 'post/index.html',context)


def tagIndex(request,tag_slug):
    post_lst = Post.objects.filter(tags__tag_text=tag_slug)
    paginator = Paginator(post_lst, 8)
    page = request.GET.get('page')
    post_list = paginator.get_page(page)
    context = {'post_list': post_list, 'tagname':tag_slug}
    return render(request, 'post/index.html',context)

@permission_required('post.can_create',login_url="authe:oops")
def create(request):
    if (request.method == 'POST'):
        form = PostForm(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.pub_date = timezone.now()
            new_post.save()
            form.save_m2m()
            return HttpResponseRedirect(reverse("post:index"))
    else:
        form = PostForm()
        pass
    return render(request, "post/create.html",{'form':form})


@permission_required('post.can_edit',login_url="authe:oops")
def edit(request,post_id):
    post = get_object_or_404(Post, pk=post_id)
    if (request.method == 'POST'):
        form = PostForm(request.POST,instance=post)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.pub_date = timezone.now()
            new_post.save()
            form.save_m2m()
            return HttpResponseRedirect(reverse("post:index"))
    else:
        form = PostForm(instance=post)
        pass
    return render(request, "post/edit.html",{'form':form, 'post_id': post_id })


@permission_required('post.can_edit',login_url="authe:oops")    
def editTags(request):
    tag_num = Tag.objects.count()
    TagFormSet = modelformset_factory(Tag,can_delete=True,fields=("tag_text",),
                                      extra=2,
                                      min_num=tag_num,
                                      max_num=20,
                                      validate_max=True,
    )
    if (request.method == 'POST'):
        formset = TagFormSet(request.POST, request.FILES)
        if formset.is_valid():
            instances = formset.save(commit=False)
            for obj in formset.deleted_objects:
                obj.delete()
                pass
            
            for instance in instances:
                instance.save()
                pass
            
            return HttpResponseRedirect(reverse("post:index"))
        pass
    else:
        formset = TagFormSet(queryset=Tag.objects.all())
        pass
    return render(request, "post/edit_tag.html",{'formset':formset})
    

class PostDelete(DeleteView):
    model = Post
    success_url = reverse_lazy('post:index')
    pass



# Create your views here.

post/templates/post/comments.html
{% load martortags %}
{% load humanize %}
<div style="margin-bottom: 110px">
  <div class="row">
    <div class="col-md-8">
      <div class="page-header">
	<h1><small class="pull-right">{{post.comment_set.all.count}} comments</small> Comments </h1>
      </div> 
      <div class="comments-list">
	{% for comment in post.comment_set.all %}
	<div class="media">
          <a class="media-left" href="#">
            <img src="http://lorempixel.com/40/40/people/1/">
          </a>
          <div class="media-body">
            <h4 class="media-heading user_name">{{ comment.user.username }}</h4>
            {{ comment.content | safe_markdown }}
          </div>
	  <p><small class="pull-right"> {{ comment.created_date | naturaltime }}</small></p> 
	</div>
	{% empty %}
	<p style="font-size:25px">No comments yet. Leave your first comment!</p>
	{% endfor %} 
      </div>
    </div>
  </div>
</div>

post/templates/post/create.html
{% extends "base_form.html" %}
{% block title %}
Create
{% endblock %}

{% block form %}

<form action="{% url 'post:create' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

{% endblock %}


{% block javascript %}
{% endblock %}

post/templates/post/detail.html
{% extends "base_posts.html" %}
{% load static %}
{% load martortags %}
{% load humanize %}
{% block css %}

<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
<link href="{% static 'plugins/css/ace.min.css' %}" type="text/css" media="all" rel="stylesheet" />
<link href="{% static 'plugins/css/semantic.min.css' %}" type="text/css" media="all" rel="stylesheet" />
<link href="{% static 'plugins/css/resizable.min.css' %}" type="text/css" media="all" rel="stylesheet" />
<link href="{% static 'martor/css/martor.min.css' %}" type="text/css" media="all" rel="stylesheet" />
{% endblock %}


{% block nested %}
<!-- Page Header -->
    <header class="masthead" style="background-image: url({% static 'img/{{post.title}}.jpg' %})">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="post-heading">
              <h1>{{ post.title }}</h1>
              <h2 class="subheading">
		{% if tags %}
		# 
		{% for tag in tags %}
		{{tag.tag_text}}<span> </span>
		{% endfor %}
		{% endif %}
	      </h2>
              <span class="meta">Posted by
                <a href="{% url 'home:about' %}">Hugo</a>
                {{post.pub_date|date:"M. d, Y"}}</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Post Content -->
    <div class="container">
      <div class="row">
    	<div class="col-lg-8 col-md-10 mx-auto">
	  {{ post.body | safe_markdown }}
    	</div>
      </div>
    </div>
    
    <hr style="margin-bottom:110px">

    {% include "post/comments.html" %}
    <hr>
    <h1>Leave Your Comment</h1>
    {% if request.user.is_authenticated %}
    <form method="POST" class="post-form">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Submit">
    </form>
    {% else %}
<p style="font-size:25px"> Please <a href="{% url 'authe:login' %}">Login</a> to comment! </p>
{% endif %}
{% endblock %}

{% block javascript %}
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/ace.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/semantic.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/mode-markdown.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/ext-language_tools.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/theme-github.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/highlight.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/resizable.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/emojis.min.js' %}"></script>
<script type="text/javascript" src="{% static 'martor/js/martor.min.js' %}"></script>
{% endblock %}

post/templates/post/edit.html
{% extends "base_form.html" %}

{% block title %}
Edit
{% endblock %}

{% block form %}
<form action="{% url 'post:edit' post_id  %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
<a href="{% url 'post:delete' post_id %}" class ="btn-sm">Delete</a>

{% endblock %}

post/templates/post/edit_tag.html
{% extends "base_form.html" %}

{% block title %}
Edit Tag
{% endblock %}

{% block form %}

<form  method="post">
  {{ formset.management_form }}
  <div id= "mark"> 
  {% for form in formset %}
  {% csrf_token %}
  {{form.as_p}}
  {% endfor %}
  </div>
  <input type="submit" value="Submit">
</form>

<div id="empty_form" style="display:none">
  {{formset.empty_form.as_p}}
</div>

<input type="button" value="Add More" id="inc">
<input type="button" value="Delete More" id="dec">
<script
  src="http://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous">
</script>
<script>
    function replace(old){
	//console.log("replace old");
	$('#mark').append($('#empty_form').html().replace(/__prefix__/g,old));
    }
$('#inc').click(function(){
    // console.log("Enter inc function");
    var total_forms = parseInt($('#id_form-TOTAL_FORMS').val());
    var max_forms = parseInt($('#id_form-MAX_NUM_FORMS').val());
    // console.log("total forms: ",total_forms);
    // console.log("max forms: ",max_forms);
    // console.log(total_forms < max_forms);
      if (total_forms < max_forms){
	  //console.log("condition satisfied");
	  var old_total = total_forms;
	  ++total_forms;
	  replace(old_total);
	  $('#id_form-TOTAL_FORMS').val(total_forms);
      }
	    
  })
$('#dec').click(function(){
    var min_forms = parseInt($('#id_form-MIN_NUM_FORMS').val());
    var dec_total_forms = parseInt($('#id_form-TOTAL_FORMS').val());
    // console.log("total forms: ",dec_total_forms);
    // console.log("min forms: ",min_forms);
      if (dec_total_forms > min_forms){
	  --dec_total_forms;
	  $("#mark p").slice(-2).remove();
	  $('#id_form-TOTAL_FORMS').val(dec_total_forms);
      }
  })
</script>
  
  
{% endblock %}

post/templates/post/index.html
{% extends "base_posts.html" %}
{% load static %}
{% load martortags %}
{% block nested %}
<!-- Navigation -->
<!-- Page Header -->
{% if tagname == "travel" %}
<header class="masthead" style="background-image: url({% static 'img/travel-bg.jpg' %})">
  {% else %}
  <header class="masthead" style="background-image: url({% static 'img/home-bg.jpg' %})">
    {% endif %}
  <div class="overlay"></div>
  <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
              <h1>HugoBlog</h1>
              <span class="subheading">
		{% if tagname == "travel" %}
		Next Stop: Japan<br>
		Interested in joining? <a style="text-decoration: underline;" href="https://goo.gl/forms/EbS4lP3jDcdPCaKg1">Here!</a>
		{% else %}
		{{tagname}}
		{% endif %}
	      </span>
            </div>
          </div>
        </div>
  </div>
</header>
<!-- Main Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
	  {% for post in post_list %}
          <div class="post-preview">
            <a href="{% url 'post:detail' post.id %}">
              <h2 class="post-title">{{post.title}}</h2>
              <!--<h3 class="post-subtitle">Problems look mighty small from 150 miles up</h3>-->
            </a>
            <p class="post-meta">Posted by
              <a href="{% url 'home:about' %}">Hugo</a>
              {{post.pub_date|date:"M. d, Y" }}</p>
	    <p class="post-meta">
	      {% if tagname == 'travel' %}
	      # travel
	      {% else %}
	      {% for tag in post.tags.all %}
	      #<a href = "{% url 'post:index_tag' tag.tag_text %}">{{tag.tag_text}}</a>
	      {% endfor %}
	      {% endif %}
	    </p>
	    <p class = "post-meta">
	      {{ post.body | safe_markdown | truncatewords:"100" }}
	    </p>
	    <p class = "post-meta">
	      <a style="text-decoration: underline; color:blue;" href="{% url 'post:detail' post.id %}"> Continue</a>
	    </p>
          </div>
          <hr>
	  {% endfor %}
          <!-- Pager -->
          <!-- <div class="clearfix"> -->
          <!--   <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a> -->
          <!-- </div> -->
        </div>
      </div>
    </div>
    {% if post_list.has_previous or post_list.has_next %}
    <hr>
    {% endif %}
    <nav aria-label="Page navigation example" style="text-align: center">
      <ul class="pagination">
	{% if post_list.has_previous %}
	<li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
	<li class="page-item"><a class="page-link" href="?page={{ post_list.previous_page_number}}">previous</a></li>
      </ul>
      {% endif %}
      {% if post_list.has_next %}
      <ul class="pagination">
	<li class="page-item"><a class="page-link" href="?page={{ post_list.next_page_number }}">next</a></li>
	<li class="page-item"><a class="page-link" href="?page={{ post_list.paginator.num_pages }}">last &raquo;</a></li>
      </ul>
      {% endif %}
    </nav>
    <hr>
{% endblock %}
    

post/templates/post/post_confirm_delete.html
<form method="post">
  {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>