authe/urls.py
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from .views import UserCreate, NotFound
from . import views
app_name = 'authe'

urlpatterns=[
    path('oops/', NotFound.as_view(),name = 'oops'),
    path('login/', auth_views.LoginView.as_view(), name = 'login' ),
    path('logout/',auth_views.LogoutView.as_view(),name = 'logout'),
    path('signup/',UserCreate.as_view(),name = 'signup'),
    path('signup/confirm/',views.signup_confirm,name='signup_confirm'),
    path('signup/activate/<uidb64>/<token>/',views.activate,name='activate'),
    path('chpwd/', views.UserChangePassword.as_view(), name='chpwd'),
    path('chpwd/success', auth_views.PasswordChangeDoneView.as_view(), name ='chpwddone'),
    path('resetpwd/',views.UserResetPassword.as_view(),name ='pwdreset'),
    path('resetpwd/confirm/<uidb64>/<token>/', views.UserResetConfirm.as_view(), name='pwdresetconfirm'),
    path('resetpwd/done',auth_views.PasswordResetDoneView.as_view(),name = 'pwdresetdone'),
    path('resetpwd/complete/',auth_views.PasswordResetCompleteView.as_view(),name ='pwdresetcomp'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from authe import views as authe_view
from django.conf import settings
from . import views
urlpatterns = [
    path('authe/', include('authe.urls')),
    path('home/', include('home.urls')),
    path('posts/',include('post.urls')),
    path('', views.redir, name = 'home_redir'),
    path('martor/',include('martor.urls')),
    
]
if settings.ADMIN_ENABLED:
    urlpatterns += [path('admin/', admin.site.urls),]
    pass

handler404 = authe_view.NotFound.as_view()

home/urls.py
from django.urls import path

from . import views
app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/',views.about,name='about'),
    path('joinme/',views.joinme,name='joinme'),
]

post/urls.py
from django.urls import path

from . import views


app_name = 'post'
urlpatterns = [
    path('',views.index,name='index'),
    path('tags/<slug:tag_slug>/',views.tagIndex, name='index_tag'),
    path('create/',views.create,name='create'),
    path('<int:post_id>/', views.detail,name='detail'),
    path('edit/<int:post_id>/',views.edit, name= 'edit'),
    path('edit/tags/',views.editTags,name='edit_tag'),
    path('delete/<int:pk>/',views.PostDelete.as_view(),name='delete'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
    <!-- Custom fonts for this template -->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="https://netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">
    {% block css %}
    {% endblock %}
  </head>
  <body>
    {% block content %}
    {% endblock %}
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    
    <!-- Custom scripts for this template -->
    <script src="{% static 'js/clean-blog.min.js' %}"></script>
    {% block javascript %}{% endblock %} 
  </body>
</html>

templates/base_auth.html
<!--https://www.tutorialrepublic.com/codelab.php?topic=bootstrap&file=simple-registration-form-->
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
    <link rel="stylesheet" type="text/css" href="{% static 'authe/auth_style.css' %}">
  </head>
  
  <body>
    {% block body %}
    {% endblock %}
  </body>
  <div style="text-align: center">
    <a style="text-align: center" class="btn btn-info btn-lg" href="{% url 'home:home' %}">Home Page</a>
  </div>
</html>

templates/base_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
     <link href="{% static 'plugins/css/ace.min.css' %}" type="text/css" media="all" rel="stylesheet" />
  <link href="{% static 'plugins/css/semantic.min.css' %}" type="text/css" media="all" rel="stylesheet" />
  <link href="{% static 'plugins/css/resizable.min.css' %}" type="text/css" media="all" rel="stylesheet" />
  <link href="{% static 'martor/css/martor.min.css' %}" type="text/css" media="all" rel="stylesheet" />
  </head>
  {% block form %}
  {% endblock %}

  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/ace.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/semantic.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/mode-markdown.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/ext-language_tools.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/theme-github.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/highlight.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/resizable.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/emojis.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'martor/js/martor.min.js' %}"></script>
  
  {% block javascript %}
  {% endblock %}

templates/base_posts.html
{% extends "base.html" %}
{% block title %}Posts{% endblock %}



{% block content %}
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="{% url 'home:home' %}">HugoBlog</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home:home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home:about' %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'post:index' %}">Post</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'post:index_tag' 'travel' %}">Travel</a>
            </li>
	    <li class="nav-item">
	      <a class="nav-link" href="{% url 'home:joinme' %}">JoinMe</a>
	    {% if user.is_authenticated %}
	    <li class="nav-item">
	      <a class="nav-link" href="{% url 'authe:logout' %}">Logout</a>
	    </li>
	    {% else %}
	    <li class="nav-item">
	      <a class="nav-link" href="{% url 'authe:signup' %}">SignUp</a>
	    </li>
	    <li class="nav-item">
	      <a class="nav-link" href="{% url 'authe:login' %}">Login</a>
	    </li>
	    {% endif %}
          </ul>
        </div>
      </div>
      {% if user.is_authenticated %}
      <div style="color:white;font-weight: bold;text-align: right"> Welcome, {{user.username}}</div>
      {% endif %}
</nav>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
{% block nested %}
{% endblock %}

<!-- Footer -->
<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="https://www.instagram.com/m.a.r.t.y.r_/">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-instagram fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="https://www.facebook.com/hugo.zhang.3979">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="https://github.com/Hugozys">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted">Copyright &copy; Hugo Zhang 2019</p>
      </div>
    </div>
      </div>
</footer>

{% endblock %}